account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

checking/urls.py
from django.urls import path
from checking.views import dashboard, checker, get_last_update

app_name = 'checking'

urlpatterns = [
    path('get_last_update', get_last_update, name='get_last_update'),
    path('checker', checker, name='checker'),
    path('', dashboard, name='dashboard'),
]

url_status/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('checking.urls', namespace='checking')),

]

account/models.py
from django.db import models

# Create your models here.

checking/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models


class Url(models.Model):
    PAUSE_CHOICES = (
        ('yes', 'Yes'),
        ('no', 'No'),
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='checking_urls')
    url = models.CharField(max_length=250)
    status_code = models.IntegerField(blank=True, null=True)
    interval = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)], help_text='in minutes')
    pause = models.CharField(max_length=3 ,choices=PAUSE_CHOICES, default='no')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('author', 'url',)
        ordering = ('-created',)

    def __str__(self):
        return self.url

account/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

account/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import LoginForm


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponse('Authenticated successfully')
            else:
                return HttpResponse('Disabled account')
        else:
            return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

checking/views.py
import requests
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.shortcuts import render
from .models import Url


@login_required
def dashboard(request):
    object_list = Url.objects.filter(author=request.user.id)
    paginator = Paginator(object_list, 10)
    page = request.GET.get('page')
    try:
        urls = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, возвращаем первую страницу.
        urls = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее количество страниц, возвращаем последнюю.
        urls = paginator.page(paginator.num_pages)
    return render(request, 'checking/dashboard.html', {'page': page, 'urls': urls})


def checker(request):
    if request.method == 'GET':
        try:
            url = Url.objects.get(id=request.GET.get('pk'))
            r = requests.get(url)
            url.status_code = r.status_code
            url.save()
            return HttpResponse(r.status_code)
        except requests.exceptions.RequestException as e:
            url.status_code = None
            url.save()
            return HttpResponse('')


def get_last_update(request):
    if request.method == 'GET':
        try:
            return HttpResponse(Url.objects.get(id=request.GET.get('pk')).updated.strftime("%Y-%m-%d %H:%M:%S"))
        except requests.exceptions.RequestException as e:
            return HttpResponse(e.errno)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
</head>
<body>
    <div id="header">
        <span class="logo">URL Status Code Checker</span>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == "dashboard" %} class="selected" {% endif %}>
                    <a href="{% url "checking:dashboard" %}">My dashboard</a>
                </li>
            </ul>
        {% endif %}

        <span class="user">
            {% if request.user.is_authenticated %}
                Hello {{ request.user.first_name }},
                <a href="{% url "logout" %}">Logout</a>
            {% else %}
                <a href="{% url "login" %}">Log-in</a>
            {% endif %}
        </span>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/checking/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}

    <script>
        check_url = function fetchdata(pk, url) {
            if (pk !== null) {
                $.ajax({
                    url: '/checker',
                    type: 'GET',
                    data: {
                        'pk': pk,
                        'url': url
                    },
                    success: function (response) {
                        if (response == 200) {
                            $('#td-' + pk).removeClass("td-red");
                            $('#td-' + pk).addClass("td-green");
                        } else {
                            $('#td-' + pk).removeClass("td-green");
                            $('#td-' + pk).addClass("td-red");
                        }
                        $.ajax({
                            url: '/get_last_update',
                            type: 'GET',
                            data: {
                                'pk': pk,
                            },
                            success: function (response) {
                                $('#td-last_check-' + pk).text(response)
                            },
                        });
                    }
                });
            }


        }
    </script>


    <table>
        <thead>
        <tr id="content-tr">
            <th>URL</th>
            <th>Status code</th>
            <th>Last check</th>
            <th>Interval(min)</th>
            <th>Pause</th>
        </tr>
        </thead>
        <tbody>
        {% for url in urls %}
            <tr>
                <td>{{ url.url }}</td>
                <td
                        {% if url.status_code == 200 %} class="td-green"
                        {% else %} class="td-red"
                        {% endif %} id="td-{{ url.id }}">

                </td>
                <td id="td-last_check-{{ url.id }}">{{ url.updated }}</td>
                <td class="td-interval" >{{ url.interval }}</td>
                <td>{{ url.pause }}</td>
            </tr>
            {% if url.pause == 'no' %}
                <script>check_url(pk={{ url.id }}, url="{{ url.url }}")
                    $(document).ready(function(){
                        setInterval(check_url,{{ url.interval }}*60000, {{ url.id }}, "{{ url.url }}");
                    });
                </script>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

{% include "checking/pagination.html" with page=urls %}


{% endblock %}

templates/checking/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>